[package]
name = "metaview"
version = "0.1.0"
authors = ["Jakub Hlusiƒçka <limeth@protonmail.com>"]
edition = "2018"

[dependencies]
ammolite = { path = "../ammolite" }
ammolite-math = { path = "../ammolite/ammolite-math" }
vulkano = { path = "../vulkano/vulkano" }
openxr = { path = "../openxrs/openxr" }
winit = "0.19.0"
paste = "0.1"
smallvec = "0.6.10"
lazy_static = "1.4.0"
# conrod = { version = "0.51.1", features = [ "piston" ] }
